spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/metaIoT
    username: op_manager
    password: meta
    driver-class-name: com.mysql.cj.jdbc.Driver

mqtt:
  topics:
    publish: op/publishments/
    ack:  op/messages/+/ack/
    completion: op/messages/+/completetion/
    rejection: op/messages/+/rejection/
  broker:
    url: ws://localhost:9001
  client:
    id: op_manager
  username: user
  password: 12345
  qos: 2
  autoReconnect: true