spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/metaIoT
    username: op_manager
    password: meta
    driver-class-name: com.mysql.cj.jdbc.Driver

mqtt:
  topics:
    publish: /op/publish/
    ack: /op/ack/
    completion: /op/completed/
    rejection: /op/rejected/
  broker:
    url: ws://localhost:9001
  client:
    id: op_manager
  username: user
  password: 12345
  qos: 0
  autoReconnect: true