spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/metaIoT
    username: op_manager
    password: meta
    driver-class-name: com.mysql.cj.jdbc.Driver

